### ISSUE TITLE
[Ubuntu] Glitch with page up or down

### ISSUE THREAD

**Issue by CanadianJeff** [traxium/tabtree#63]
not sure if this is really a bug but on some pages when trying to click on a page and press page up or down to scroll the page the tab tree will scroll instead

**Comment by traxium** [comment]
Fixed in 38e9fda0bdf316dba345a9c717e62a4d44ce993c. And arrow up/down keys are also fixed in that manner. This glitch happened when the tree was focused (e.g. clicking tree's scroll bar focuses it or clicking empty area below the "tabs"). The fix will be available in the next version (1.4.3).
Thank you for reporting the issue.

**Comment by traxium** [comment]
The bug is fixed. I'll close the issue.
